-- Consulte  as  duas  cidades  em  STATION  com  os  nomes  (CITY)  mais  curto  e  mais  longo,  bem  como  seus  respectivos 
-- comprimentos (ou seja, número de caracteres do nome mais curto e mais longo). Se houver mais de uma cidade menor 
-- ou  maior,  escolha  a  que  ocorrer  primeiro  em  ordem  alfabética.  Os  nomes  das  colunas  retornadas  devem  ser  os 
-- seguintes: NOME_MENOR, NOME_MAIOR, TAM_MENOR, TAM_MAIOR

--SELECT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) ASC, CITY ASC LIMIT 1;  -- menor
-- SELECT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) DESC, CITY ASC LIMIT 1; -- maior




SELECT 
    CITY FROM STATION  ORDER BY LENGTH(CITY) ASC, CITY ASC LIMIT 1 AS NOME_MENOR,
    CITY FROM STATION ORDER BY LENGTH(CITY) DESC, CITY ASC LIMIT 1 AS NOME_MAIOR,
    LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) ASC, CITY ASC LIMIT 1 AS TAM_MENOR,
    LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) DESC, CITY ASC LIMIT 1 AS TAM_MAIOR

SELECT 
    MIN(CITY) AS NOME_MENOR, 
    MAX(CITY) AS NOME_MAIOR, 
    LENGTH(MIN(CITY)) AS TAM_MENOR, 
    LENGTH(MAX(CITY)) AS TAM_MAIOR
FROM STATION
WHERE LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION)
   OR LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION)
ORDER BY CITY;

SELECT 
MIN(CITY) AS NOME_MENOR,
MAX(CITY) AS NOME_MAIOR
FROM STATION
WHERE LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION) OR (SELECT MAX(LENGTH(CITY)) FROM STATION) 




SELE